#!/bin/bash

# Prompt
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
cyan=$(tput setaf 6)
blue=$(tput setaf 4)
bold=$(tput bold)
reset=$(tput sgr0)

function ps1_k8s_context {
    K8S_CONTEXT=$(kubectl config current-context 2>/dev/null| cut -d/ -f1)
    if [ -z "$K8S_CONTEXT" ]; then
        return 
    else
        echo -n "(k8s:$K8S_CONTEXT)"
    fi
}

function ps1_currdir {
    prefix="/"
    current_dir=$(pwd)
    suffix=$(echo $current_dir | rev | cut -d"/" -f1,2 | rev)
    dirlevel=$(echo $current_dir | grep -o "/" | wc -l)
    if [ $dirlevel -gt 2 ]; then
        prefix="*/"
    elif [ $dirlevel -eq 1 ]; then
        prefix=""
    fi

    echo -n "$prefix$suffix"
}

function ps1_gbranch {
    gbranch=$(git branch --show-current 2> /dev/null)
    if [ $? != 0 ]; then
        return
    fi
    status=$(git status -s 2> /dev/null)
    untracked=""
    changed=""
    ok="✔"
    if [ $(echo $status | egrep -c -m 1 '\?\? ') -eq 1 ]; then
        untracked="?"
        ok=""
    fi
    if [ $(echo $status | egrep -c -m 1 'M ') -eq 1 ]; then
        changed="M"
        ok=""
    fi
    color=$green
    #echo -en '\033[34m'
    if [ "$gbranch" == "main" ] || [ "$gbranch" == "master" ]; then
        #echo -en '\033[32m'
        color=$red
    fi
    echo -en "\001$color\002($untracked$changed$ok $gbranch)\001$reset\002 "
}

function ps1_exit {
    prev_exit=$?
    if [ $prev_exit -ne 0 ]; then
        echo -n "[$prev_exit]"
    else
        return 
    fi
}

function ps1_aws_env {
    if [ -z "$AWS_PROFILE" ]; then
        return 
    else
        output=$(echo "$AWS_VAULT$AWS_PROFILE" | sed -e 's/[cC]onstellation-//')
        echo -n "(aws:$output)"
    fi
}

export PS1="\[$red\]\$(ps1_exit)\[$reset\]\[$cyan\][\A]\[$reset\]\[$blue\]\$(ps1_k8s_context)\[$reset\]\[$yellow\]\$(ps1_aws_env)\[$reset\] \[$bold\]\u\[$reset\]@\[$bold\]\h\[$reset\] \[$green\]\$(ps1_gbranch)\[$reset\]\$(ps1_currdir) \[$bold\]$>\[$reset\] "

# Aliases and Functions
#Util Options 
# ===Start===
if [ `uname | grep -c Linux` == 0 ]; then
    alias ls="ls -G"
    alias sed="gsed"
else
    alias ls="ls --color=auto"
fi
# ====End====

#TMUX
# ===Start===
#copy buffer control
alias tlist="tmux list-buffers"
alias tdel="tmux delete-buffer"
alias tin='tmux set-buffer "`cat -`"'

tmux-bankruptcy () {
    ps -ef | grep v[i]m | awk '{print $2}' | xargs kill -SIGTERM
    ll=$(tmux list-windows | wc -l)
    lm=$(bc <<< "$ll-1")
    tmux list-windows | tail -n $lm | cut -d: -f1 | while read line; do tmux kill-window -t $line; done
}

tclean () {
    for x in `seq $1 $2`; do
        tmux kill-window -t $x;
    done;
}

tout () {
    if [ "$1" != "" ]; then
        tmux show-buffer -b $1
    else
        tmux show-buffer
    fi
}
# ====End====
 
#Vim workflow
# ===Start===
alias typewriter="tmux splitw -h -p 80 ; tmux splitw -h -p 25; tmux send-keys -t:.1 'vim -c Word' Enter; tmux clock; tmux select-pane -t:.1"
# ====End====

#K8s workflow
# ===Start===
alias kkns='kubectl get ns -o name | cut -d/ -f2 | fzf | xargs kubectl config set-context --current --namespace'
alias kkc='kubectl config get-contexts -o name | fzf | xargs kubectl config use-context'
kkget () {
    kubectl get $1 -o name | fzf | xargs kubectl get -o yaml
}
kkdesc () {
    kubectl get $1 -o name | fzf | xargs kubectl describe
}
# ====End====

#Random utils
# ===Start===
alias rand='python -c "import base64, os, sys; print(base64.b64encode(os.urandom(int(sys.argv[1])*3)).replace(\"+\",\"\").replace(\"/\",\"\")[:int(sys.argv[1])] if len(sys.argv)>1 else \"Nope\")"'
alias breakdown='sort | uniq -c | sort -nr'
alias flushdnsmac='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias assume=". assume"
# ====End====

# NVM
# ===Start===
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" || echo -n ""  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" || echo -n ""  # This loads nvm bash_completion
# ====End====
