#!/bin/bash
if [ "$EUID" -ne 0 ]; then
    echo "Run me as root"
    exit 1
fi

cp files/xorg.conf.intel /etc/X11/xorg.conf.intel
cp files/xorg.conf.nvidia /etc/X11/xorg.conf.nvidia

cp files/sources.list /etc/apt/sources.list

apt-get update

# update tlp for battery gains
# install dkms, build tools, headers
# install wifi firmware
apt-get install -y build-essential make gcc tmux dkms tlp tp-smapi-dkms acpi-call firmware-iwlwifi apt-file mesa-utils linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,')

# build/install nvidia-driver
apt-get install -y nvidia-driver

# Link up the correct x config
if [ $(lspci | grep -ci nvidia) -gt 0 ]; then
    #nvidia card enabled
    ln -sf /etc/X11/xorg.conf.nvidia /etc/X11/xorg.conf
else
    #nvidia card disabled
    ln -sf /etc/X11/xorg.conf.intel /etc/X11/xorg.conf
fi



