#!/bin/bash

#Util Options 
# ===Start===
if [ `uname | grep -c Linux` == 0 ]; then
    alias ls="ls -G"
    alias sed="gsed"
else
    alias ls="ls --color=auto"
fi
# ====End====

#TMUX
# ===Start===
ssh-landing () {
    if [ $(tmux ls | grep -v detached | grep -c misc) -gt 0 ]; then
        tmux a -t misc;
    else
        tmux new-session -s misc;
    fi
}

#copy buffer control
alias tlist="tmux list-buffers"
alias tdel="tmux delete-buffer"
alias tin='tmux set-buffer "`cat -`"'

tmux-bankruptcy () {
    ps -ef | grep v[i]m | awk '{print $2}' | xargs kill -SIGTERM
    ll=$(tmux list-windows | wc -l)
    lm=$(bc <<< "$ll-1")
    tmux list-windows | tail -n $lm | cut -d: -f1 | while read line; do tmux kill-window -t $line; done
}

tclean () {
    for x in `seq $1 $2`; do
        tmux kill-window -t $x;
    done;
}

tout () {
    if [ "$1" != "" ]; then
        tmux show-buffer -b $1
    else
        tmux show-buffer
    fi
}
# ====End====
 
#Clipboard
# ===Start===
alias cbin='xclip -in -selection clipboard'
alias cbout='xclip -out -selection clipboard'
# ====End====

#Vim workflow
# ===Start===
alias typewriter="tmux splitw -h -p 80 ; tmux splitw -h -p 25; tmux send-keys -t:.1 'vim -c Word' Enter; tmux clock; tmux select-pane -t:.1"
# ====End====

#Python workflow
# ===Start===
qvenv () {
    source ~/venvs/$1/bin/activate
}
# ====End====

#Go workflow
# ===Start===
alias gohere='export GOPATH=`pwd`:$GOPATH'
alias goaway='unset GOPATH'
# ====End====

#Random utils
# ===Start===
alias rand='python -c "import base64, os, sys; print(base64.b64encode(os.urandom(int(sys.argv[1])*3)).replace(\"+\",\"\").replace(\"/\",\"\")[:int(sys.argv[1])] if len(sys.argv)>1 else \"You are fake news\")"'
alias breakdown='sort | uniq -c | sort -nr'
alias wotd='curl -s -L "https://www.merriam-webster.com/word-of-the-day"| grep "<h1>" | sed -e "s|.*<h1>\(.*\)</h1>.*|\1|"'
alias castnow='castnow -ip chromeduck'
alias flushdnsmac='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
screengrab () {
    filename=`date +%Y-%M-%d_%H:%M`.png
    filepath=~/Pictures/scrots
    scrot -s $filepath/$filename
    ln -sf $filepath/$filename $filepath/latest.png
    firefox $filepath/latest.png
}
# ====End====
