#!/bin/bash

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
cyan=$(tput setaf 6)
reset=$(tput sgr0)

function ps1_currdir {
    prefix="/"
    current_dir=$(pwd)
    suffix=$(echo $current_dir | rev | cut -d"/" -f1,2 | rev)
    dirlevel=$(echo $current_dir | grep -o "/" | wc -l)
    if [ $dirlevel -gt 2 ]; then
        prefix="*/"
    elif [ $dirlevel -eq 1 ]; then
        prefix=""
    fi

    echo -n "$prefix$suffix"
}

function ps1_gbranch {
    gbranch=$(git branch --show-current 2> /dev/null)
    if [ $? != 0 ]; then
        return
    fi
    status=$(git status -s 2> /dev/null)
    untracked=""
    changed=""
    ok="✔"
    if [ $(echo $status | egrep -c -m 1 '\?\? ') -eq 1 ]; then
        untracked="?"
        ok=""
    fi
    if [ $(echo $status | egrep -c -m 1 'M ') -eq 1 ]; then
        changed="M"
        ok=""
    fi
    color=$green
    #echo -en '\033[34m'
    if [ "$gbranch" == "main" ] || [ "$gbranch" == "master" ]; then
        #echo -en '\033[32m'
        color=$red
    fi
    echo -en "\001$color\002($untracked$changed$ok $gbranch)\001$reset\002 "
}

function ps1_exit {
    prev_exit=$?
    if [ $prev_exit -ne 0 ]; then
        echo -n "[$prev_exit]"
    else
        return 
    fi
}

function ps1_go_env {
    if [ -z "$GOPATH" ]; then
        return 
    else
        output=$(echo $GOPATH | rev | cut -d'/' -f1 | rev)
        echo -n "($output)"
    fi
}

function ps1_aws_env {
    if [ -z "$AWS_REGION" ]; then
        return 
    else
        output=$(echo "$AWS_VAULT$AWS_PROFILE:$AWS_REGION")
        echo -n "($output)"
    fi
}

export PS1="\[$red\]\$(ps1_exit)\[$reset\]\[$cyan\][\A]\[$reset\]\[$yellow\]\$(ps1_aws_env)\$(ps1_go_env)\[$reset\] \u@\h \[$green\]\$(ps1_gbranch)\[$reset\]\$(ps1_currdir) $> "
